spring:
  application:
    name: idemotent
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=kafkadb&ssl=false #change this to your database url
    password: oracle #change this to your database username
    username: postgres #change this to your database password

    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092